ALTER TABLE posts 
ADD COLUMN event_id UUID REFERENCES events(id) ON DELETE SET NULL,
ADD COLUMN building_id UUID REFERENCES buildings(id) ON DELETE SET NULL,
ADD COLUMN room_id UUID REFERENCES rooms(id) ON DELETE SET NULL;
