apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: hustsim
  labels:
    app: social-service
    app.kubernetes.io/part-of: hustsimulator
spec:
  type: ClusterIP
  selector:
    app: social-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
    - port: 9092
      targetPort: 9092
      name: socketio
