apiVersion: v1
kind: Service
metadata:
  name: state-dissemination-service
  namespace: hustsim
  labels:
    app: state-dissemination-service
    app.kubernetes.io/part-of: hustsimulator
spec:
  type: ClusterIP
  selector:
    app: state-dissemination-service
  ports:
    - port: 3002
      targetPort: 3002
      name: ws
