export enum UserActivityState {
  ROAMING = 'ROAMING',
  IN_RECURRING_EVENT = 'IN_RECURRING_EVENT',
  IN_EVENT = 'IN_EVENT',
  OUTSIDE_MAP = 'OUTSIDE_MAP',
  IN_BUILDING = 'IN_BUILDING',
  SPECTATING_BUILDING = 'SPECTATING_BUILDING',
  IN_ROOM = 'IN_ROOM',
  SPECTATING_EVENT = 'SPECTATING_EVENT',
  SPECTATING_RECURRING_EVENT = 'SPECTATING_RECURRING_EVENT',
}
