apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: hustsim
  labels:
    app: prediction-service
    app.kubernetes.io/part-of: hustsimulator
spec:
  type: ClusterIP
  selector:
    app: prediction-service
  ports:
    - port: 50055
      targetPort: 50055
      name: grpc
    - port: 50056
      targetPort: 50056
      name: http
