apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hustsim
  labels:
    app: auth-service
    app.kubernetes.io/part-of: hustsimulator
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
