ALTER TABLE context.rooms 
ADD COLUMN IF NOT EXISTS capacity INT,
ADD COLUMN IF NOT EXISTS floor_num INT,
ADD COLUMN IF NOT EXISTS type TEXT,
ADD COLUMN IF NOT EXISTS phone_num TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS website TEXT;
