UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C1.png' WHERE name = 'C1';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C10.png' WHERE name = 'C10';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C2.png' WHERE name = 'C2';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C3-4.png' WHERE name = 'C3-4';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C3.png' WHERE name = 'C3';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C3B.png' WHERE name = 'C3b';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C4.png' WHERE name = 'C4';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C5.png' WHERE name = 'C5';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/C7.png' WHERE name = 'C7';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D2A.png' WHERE name = 'D2A';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D3-5.png' WHERE name = 'D3-5';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D3.png' WHERE name = 'D3';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D6.png' WHERE name = 'D6';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D8.png' WHERE name = 'D8';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/D9.png' WHERE name = 'D9';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/KTX-B7.png' WHERE name = 'Ký túc xá B7';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/SVD.png' WHERE name = 'Sân vận động Bách Khoa';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/San-bong-ro-ktx.png' WHERE name = 'Sân bóng rổ KTX Bách Khoa';
UPDATE buildings SET image_url = 'https://storage.googleapis.com/hustsimulator-storage/building-images/Thuvien.png' WHERE name = 'Thư viện Tạ Quang Bửu';
